version: '3'

services:
    web:
        build: './Dockerfile/Php/7.4'
        image: hakankaya/centos-php:7.7
        working_dir: /var/www/html/anilarimiz/laravel
        restart: always
        ports:
            - '80:80'
            - '8000:8000'
        depends_on:
        #   - postgres
            - mysql
            - redis
        links:
        #    - postgres
            - mysql
            - redis
        volumes:
            - ./www:/var/www/html:cached
            - ./config/vhost.conf:/etc/httpd/conf.d/vhost.conf
            - ./config/phpMyAdmin.conf:/etc/httpd/conf.d/phpMyAdmin.conf
            - ./config/config.inc.php:/etc/phpMyAdmin/config.inc.php
            - ./config/php.ini:/etc/php.d/php.ini
            #- ./config/xdebug.ini:/etc/php.d/xdebug.ini
            #- /Volumes/a/2018-2019-OKULLAR/istem koleji:/var/www/html/anilarimiz/public_html/okul
            
        extra_hosts:
            - "docker-host.localhost:127.0.0.1" #Host Dosyasına ekliyor

        networks:
            app_network:
                ipv4_address: 192.168.2.2
                    
    mysql:
        image: mariadb:10.5.3-bionic
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 3145
            TZ : Europe/Istanbul
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            app_network:
                ipv4_address: 192.168.2.3

    redis:
        image: redis:latest
        restart: always
        command: redis-server --requirepass 3145
        volumes:
            - redis_data:/var/lib/redis
        ports:
            - '6379:6379'
        networks:
            app_network:
                ipv4_address: 192.168.2.4

   # postgres:
       # image: postgres:11
        #environment:
         #   POSTGRES_USER: postgres
          #  POSTGRES_PASSWORD: 3145
           # TZ : Europe/Istanbul
       # volumes:
           # - postgres_data:/var/lib/postgresql/data
       # ports:
           # - '5432:5432'
        #networks:
            #app_network:
              #  ipv4_address: 192.168.2.4

volumes:
    mariadb_data:
        external: true
        
    postgres_data:
        external: true

    redis_data:
        external: true

networks:
    app_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.2.0/24