version: '3'

services:
    web:
        build: './Dockerfile/Php/7.2'
        image: hakankaya/centos-php:7.2
        working_dir: /var/www/html/
        restart: always
        ports:
            - '80:80'
            - '8000:8000'
        depends_on:
        #   - postgres
            - mysql
        links:
        #    - postgres
            - mysql
        volumes:
            - ./www:/var/www/html:cached
            - ./config/vhost.conf:/etc/httpd/conf.d/vhost.conf
            - ./config/phpMyAdmin.conf:/etc/httpd/conf.d/phpMyAdmin.conf
            - ./config/config.inc.php:/etc/phpMyAdmin/config.inc.php
            - ./config/php.ini:/etc/php.d/php.ini
            #- ./config/xdebug.ini:/etc/php.d/xdebug.ini
            #- /Volumes/a/2018-2019-OKULLAR/istem koleji:/var/www/html/anilarimiz/public_html/okul
            
        extra_hosts:
            - "docker-host.localhost:127.0.0.1" #Host Dosyasına ekliyor

        networks:
            app_network:
                ipv4_address: 192.168.2.2
                    
    mysql:
        image: mariadb:10.5.1-bionic
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 3145
            TZ : Europe/Istanbul
        volumes:
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        ports:
            - '3306:3306'
        networks:
            app_network:
                ipv4_address: 192.168.2.3

   # postgres:
       # image: postgres:11
        #environment:
         #   POSTGRES_USER: postgres
          #  POSTGRES_PASSWORD: 3145
           # TZ : Europe/Istanbul
       # volumes:
           # - postgres_data:/var/lib/postgresql/data
       # ports:
           # - '5432:5432'
        #networks:
            #app_network:
              #  ipv4_address: 192.168.2.4

#volumes:
    #mariadb_data:
        #external: true
        
    #postgres_data:
        #external: true

networks:
    app_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.2.0/24